[project]
name = "py-scripts"
version = "0.1.0"
description = "Shared Python scripts"
requires-python = ">=3.13"

[dependency-groups]
dev = [
  "coverage (>=7.13.2,<8.0.0)",
]

[tool.poetry]
package-mode = false
