[project]
name = "ig-py-lib"
version = "0.1.0"
description = "Shared Python utilities"
requires-python = ">=3.13"

dependencies = [
  "redis (>=7.1.0,<8.0.0)",
  "websockets (>=16.0,<17.0)",
  "pyjwt (>=2.11.0,<3.0.0)",
  "psutil (>=7.2.2,<8.0.0)",
  "types-psutil (>=7.2.2.20260130,<8.0.0.0)"
]

[dependency-groups]
dev = [
  "pytest (>=9.0.2,<10.0.0)",
  "pytest-asyncio (>=1.3.0,<2.0.0)",
  "pytest-cov (>=7.0.0,<8.0.0)",
  "pytest-mock (>=3.15.1,<4.0.0)",
  "coverage (>=7.13.2,<8.0.0)",
  "mypy (>=1.19.1,<2.0.0)",
  "ruff (>=0.14.14,<0.15.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "ig_py_lib", from = "src" }]
include = ["src/ig_py_lib/py.typed"]
